# Jekyll Configuration
lang: zh-CN
timezone: Asia/Shanghai

# Site Settings
title: 董嘉铖的博客
tagline: 3D Vision & AI Research Blog
description: >-
  董嘉铖的个人博客，专注于3D视觉、3D高斯散射、深度学习等领域的技术分享与研究心得。

# fill in the protocol & hostname for your site
# e.g. https://username.github.io
url: "https://dongjiacheng06.github.io"

# the base hostname & protocol for your site
baseurl: "/dongjiacheng06-blog"

github:
  username: dongjiacheng06

social:
  # Change to your full name.
  name: Jiacheng Dong
  email: Dong48@illinois.edu
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/dongjiacheng06

# Avatar设置
avatar: "/assets/images/personal_photo.jpg"

# Theme (remote_theme for GitHub Pages compatibility)
remote_theme: cotes2020/jekyll-theme-chirpy@v7.0.1

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-redirect-from

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge

# 确保文章显示在首页
future: true
show_excerpts: true

# Collections
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Jekyll Archives for categories and tags
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE